version: "3"
services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./project:/var/www/html/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    networks:
      - web-server
  php:
    build: ./php/
    container_name: php-72
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./project:/var/www/html/project
      - ./php:/usr/local/etc/php
    networks:
      - web-server
  mysql:
    image: mysql:5.7
    container_name: mysql-57
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - TZ=Asia/Taipei
      - MYSQL_ROOT_PASSWORD=123456
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - web-server
  #redis:
  #  image: redis:latest
  #  container_name: redis
  #  restart: always
  #  ports:
  #    - "6379:6379"
  #  volumes:
  #    - ./redis/data:/usr/local/etc/redis
  #  command: redis-server /usr/local/etc/redis/redis.conf
networks:
  web-server: